services:
  - type: web
    name: spotik-gpt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level debug
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: LOG_LEVEL
        value: "DEBUG"
